[window]
option_as_alt= "Both"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.normal]
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[shell]
args = ["--login", "-c", "tmux attach || tmux new -s new-session"]
program = "/bin/zsh"
