[window]
option_as_alt= "Both"

[colors]
draw_bold_text_with_bright_colors = true

#[colors.bright]
#black = "#4D453E"
#blue = "#9AACCE"
#cyan = "#88B3B2"
#green = "#99D59D"
#magenta = "#CE9BCB"
#red = "#F17C64"
#white = "#C1A78E"
#yellow = "#EBC06D"

#[colors.normal]
#black = "#352F2A"
#blue = "#9AACCE"
#cyan = "#86A3A3"
#green = "#78997A"
#magenta = "#B380B0"
#red = "#B65C60"
#white = "#A38D78"
#yellow = "#EBC06D"

#[colors.primary]
#background = "#2A2520"
#foreground = "#ECE1D7"

[font]
size = 14.0

[font.normal]
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[shell]
args = ["--login", "-c", "tmux attach || tmux new -s new-session"]
program = "/bin/zsh"
